import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useSelector } from "react-redux";

import { wrapper } from "app/store";
import { selectProfile, setProfileData } from "app/store/slices/profile";
import styles from "../styles/Home.module.css";

const Profile: NextPage = (props: any) => {
  const { resolvedUrl } = props;
  const profile = useSelector(selectProfile) as any;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <h1>URL: {resolvedUrl}</h1>
        <p>
          This is the Redux data set in Index: <strong> {profile.name}</strong>
        </p>

        <p>
          Navigate to
          <Link href="/" legacyBehavior>
            <a>
              <strong> Home</strong>
            </a>
          </Link>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    async ({ resolvedUrl }) => {
      return {
        props: { resolvedUrl },
      };
    }
);

export default Profile;
